42-ft-transcendence/ft_transcendence_front

application/svelte.config.js

fix: rename fallback file

---

application/src/routes/channel/[id]/+page.svelte

page안의 채팅창 크기 조절(height: 100%)을 통해 해결.
#5

fix: chat promt position

---

application/src/routes/+layout.svelte
application/src/routes/+layout.ts
application/src/routes/login/+page.svelte

feat: login page

---

application/src/routes/signup/+page.svelte

feat: signup page.

---

application/src/lib/ContextMenu/FollowContextMenu.svelte
application/src/lib/Modal/SearchFollowModal.svelte
application/src/lib/Modal/ShowChannelInfoModal.svelte
application/src/lib/Sidebar/ChatNavigation.svelte
application/src/lib/common.ts
application/src/lib/store.ts
application/src/lib/type.ts
application/src/routes/+layout.svelte
application/src/routes/+layout.ts

기능 구현 및 수정

---

application/src/lib/ContextMenu/ChannelContextMenu.svelte
application/src/lib/ContextMenu/DMContextMenu.svelte
application/src/lib/ContextMenu/FollowContextMenu.svelte
application/src/lib/Modal/CreateChannelModal.svelte
application/src/lib/Modal/SearchChannelModal.svelte
application/src/lib/Modal/ShowChannelInfoModal.svelte
application/src/lib/Sidebar/ChatNavigation.svelte
application/src/lib/common.ts
application/src/routes/+layout.svelte
application/src/routes/channel/[id]/+page.svelte

Socket feat

---

application/src/routes/+page.svelte

feat: game page

---

application/src/routes/+page.svelte
application/src/routes/game/+page.svelte

+page.svelte 내용 ./game/+page.svelte로 이동 및 기존 내용 복원

fix: game 내용 경로 변경

---

application/src/routes/signup/+page.svelte

signup 페이지에서 버튼을 연속으로 누르지 못하게 progressredials 추가

feat: progressRadials in sginup

---

application/src/routes/+layout.svelte
application/src/routes/channel/[id]/+page.svelte

fix: 줄바뀜 안되는 문제

---

application/src/routes/+layout.svelte

socket 연결시 정의 되지않은 타입으로 token 정의 하는 부분 수정

chore: auth redefine

---

application/src/lib/Sidebar/Navigation.svelte
application/src/lib/Sidebar/Profile.svelte

fix: remove hidden scroll

---

application/src/lib/Game/Game.svelte
application/src/routes/+layout.svelte

feat: game reconnection

---

application/src/lib/Game/Game.svelte
application/src/routes/game/+page.svelte

chore: auto-subscriptions

---

application/src/routes/+layout.svelte

fix: rename socket event 'goto Game'

fix: rename socket event 'goto Game'

---

application/src/lib/Modal/SearchChannelModal.svelte
application/src/lib/Modal/SearchFollowModal.svelte
application/src/lib/Modal/ShowMatchHistoryModal.svelte
application/src/lib/Modal/StartDirectMessage.svelte
application/src/lib/Sidebar/Profile.svelte
application/src/lib/type.ts
application/src/routes/+layout.svelte
application/src/routes/channel/[id]/+page.svelte

- 사용자의 매치 히스토리를 다 보여주는 모달 구현
- 스토어 subscribe 메모리 누수 관리
- 채팅 관련 500자 입력 제한

feat: 기능 구현

---

application/src/lib/Game/Game.svelte
application/src/routes/+layout.svelte
application/src/routes/game/+page.svelte

chore: restore goto Url and duplicated func

chore: restore goto Url and duplicated func

---

application/src/routes/+page.svelte
application/src/routes/game/+page.svelte

chore: 메인페이지 수정 및 게임모드 설명

---

application/src/routes/+page.svelte

fix: rename PonGo in main page

fix: rename PonGo in main page

---

application/src/routes/+layout.svelte

fix: leave room

---

application/src/lib/Game/Game.svelte

fix: player init position
